name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Version check
      run: cargo --version
    - name: Build
      run: cargo build --features "strict"
    - name: Run tests
      run: cargo test
