name: Rust

on: [push]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test

  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Version check
      run: cargo --version
    - name: Build
      run: cargo build --features "strict"
